{% set name = "gramex" %}
{% set version = "1.60.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 920a7b0c5cd031ee6632392bd37cabfe59bf2fd24958d65e3f453a97ad986e5c

build:
  number: 3
  entry_points:
    - gramex = gramex:commandline

requirements:
  build:
    - pip
    - setuptools
    - python
    - colorama
    - h5py
    - lxml
    - matplotlib
    - pandas
    - pytest
    - seaborn
    - sqlalchemy
    - rpy2
    - tzlocal
    - scikit-learn
    - pyyaml>=5.1
  run:
    - python
    - pip
    - nodejs>=7.6
    - argh>=0.24.1
    - boto3>=1.5
    - cachetools>=3.0.0
    - colorama
    - colorlog>=2.7.0
    - conda
    - crontab>=0.21
    - cssselect
    - diskcache>=2.8.3
    - h5py
    - inflect
    - ipdb
    - jmespath
    - joblib
    - ldap3>=2.2.4
    - lxml
    - markdown
    - matplotlib
    - oauthlib>=1.1.2
    - pandas
    - passlib>=1.6.5
    - pathlib
    - pathtools>=0.1.1
    - psutil
    - pymysql
    - pytest
    - python-pptx>=0.6.6
    - pyyaml>=5.1
    - redis>=2.10.0
    - requests
    - rpy2
    - seaborn
    - scikit-learn
    - selenium
    - setuptools>=16.0
    - shutilwhich>=1.1.0
    - six
    - sqlalchemy
    - sqlitedict>=1.5.0
    - textblob
    - tornado ==5.1.1
    - watchdog>=0.8
    - xlrd
    - yarn
test:
  imports:
    - gramex
  commands:
    - gramex
    - gramex setup --all

about:
  home: http://learn.gramener.com/guide/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Gramex - Visual Analytics Platform.
  doc_url: https://learn.gramener.com/guide
  dev_url: https://github.com/gramener/gramex

extra:
  recipe-maintainers:
    - jaidevd
