{% set name = "gramex" %}
{% set version = "1.62.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 494a9c152c096e6b4eec089c5fb223b67f330ef792449d3e089d7ecc430825cf

build:
  number: 1
  entry_points:
    - gramex = gramex:commandline
    - slidesense = gramex.pptgen2:commandline

requirements:
  build:
    - pip
    - setuptools
    - python
    - colorama
    - h5py
    - lxml
    - matplotlib
    - pandas
    - pytest
    - seaborn
    - sqlalchemy
    - tzlocal
    - scikit-learn
    - pyyaml>=5.1
  run:
    - python
    - pip
    - nodejs>=7.6
    - colorama
    - conda
    - h5py
    - joblib
    - lxml
    - matplotlib
    - pandas
    - pytest
    - requests
    - seaborn
    - scikit-learn
    - setuptools>=16.0
    - shutilwhich>=1.1.0
    - sqlalchemy
    - yarn
    - tzlocal

test:
  imports:
    - gramex
  commands:
    - gramex

about:
  home: http://learn.gramener.com/guide/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Gramex - Visual Analytics Platform.
  doc_url: https://learn.gramener.com/guide
  dev_url: https://github.com/gramener/gramex

extra:
  recipe-maintainers:
    - jaidevd
