{% set name = "gramex" %}
{% set version = "1.60.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 920a7b0c5cd031ee6632392bd37cabfe59bf2fd24958d65e3f453a97ad986e5c
  patches:
    - nlg-setup.patch

build:
  number: 5
  entry_points:
    - gramex = gramex:commandline

requirements:
  build:
    - pip
    - setuptools
    - python
    - colorama
    - h5py
    - lxml
    - matplotlib
    - pandas
    - pytest
    - seaborn
    - sqlalchemy
    - tzlocal
    - scikit-learn
    - pyyaml>=5.1
    - r-base
    - r-essentials
  run:
    - python
    - pip
    - nodejs>=7.6
    - colorama
    - conda
    - h5py
    - joblib
    - lxml
    - matplotlib
    - pandas
    - pytest
    - requests
    - seaborn
    - scikit-learn
    - setuptools>=16.0
    - shutilwhich>=1.1.0
    - sqlalchemy
    - yarn
    - r-base
    - r-essentials
test:
  imports:
    - gramex
  commands:
    - gramex

about:
  home: http://learn.gramener.com/guide/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Gramex - Visual Analytics Platform.
  doc_url: https://learn.gramener.com/guide
  dev_url: https://github.com/gramener/gramex

extra:
  recipe-maintainers:
    - jaidevd
