{% set name = "gramex" %}
{% set version = "1.61.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 42325ac89863a6a90a3f6b95ce89fc6d0d6929a4f40bb52d3c4831bf63b54007

build:
  number: 5
  entry_points:
    - gramex = gramex:commandline

requirements:
  build:
    - pip
    - setuptools
    - python
    - colorama
    - h5py
    - lxml
    - matplotlib
    - pandas
    - pytest
    - seaborn
    - sqlalchemy
    - tzlocal
    - scikit-learn
    - pyyaml>=5.1
  run:
    - python
    - pip
    - nodejs>=7.6
    - colorama
    - conda
    - h5py
    - joblib
    - lxml
    - matplotlib
    - pandas
    - pytest
    - requests
    - seaborn
    - scikit-learn
    - setuptools>=16.0
    - shutilwhich>=1.1.0
    - sqlalchemy
    - yarn
    - tzlocal
test:
  imports:
    - gramex
  commands:
    - gramex

about:
  home: http://learn.gramener.com/guide/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Gramex - Visual Analytics Platform.
  doc_url: https://learn.gramener.com/guide
  dev_url: https://github.com/gramener/gramex

extra:
  recipe-maintainers:
    - jaidevd
